### ISSUE TITLE
String types are hidden from VSCode autocompletion

### ISSUE THREAD

**Issue by rshackleton** [dohomi/storyblok-generate-ts#13] opened 2022-08-12 18:29 UTC
All required string fields are hidden from VS Code autocompletion due to them being masked by `[k: string]: any;`

```
export interface PageStoryblok {
  title: string;
  body?: any[];
  _uid: string;
  component: "page";
  uuid?: string;
  [k: string]: any;
}
```

![image](https://user-images.githubusercontent.com/13448395/184421406-a555b52c-3965-4b7d-a6f8-b959eec3f502.png)

```
export interface PageStoryblok {
  title: string;
  body?: any[];
  _uid: string;
  component: 'page';
  uuid?: string;
}
```

![image](https://user-images.githubusercontent.com/13448395/184421446-73cad637-3a3f-4cb5-8eb3-bb84a02074ae.png)

**Comment by rshackleton** [comment] 2022-08-12 18:33
I think `additionalProperties` needs to be set to `false` on the calls to `compile`.

**Comment by dohomi** [comment] 2022-08-14 03:47
I can't reproduce this issue. I am using Webstorm and never faced an issue. If you find a solution please open a PR

**Comment by rshackleton** [comment] 2022-08-14 16:10
Perhaps Webstorm handles the type differently, it appears that VSCode hides string properties on the type definition if they match an indexer. The "fix" would be to remove `[k: string]: any;` which feels appropriate since there shouldn't be undocumented properties anyway?

**Comment by dohomi** [comment] 2022-08-15 13:17
this library uses json-schema-to-typescript under the hood and I use it for over 2 years in production. If you find a fix for VS please open a PR I just never bumped into it and don't know how to fix it.

**Comment by brianmorin-ef** [comment] 2022-10-06 16:43
+1 on setting `additionalProperties` to false when calling json-schema-to-typescript. The types as they're generated now are too lenient to provide type safety because of `[k: string]: any;`. Perhaps the library could accept an options object to pass into json-schema-to-typescript that would allow for the user to decide `additionalProperties` for their use case, set the banner comment, etc?

**Comment by dohomi** [comment] 2022-10-07 02:07
I would be happy to review a PR on this matter. Maybe the CLI would take a property to disable `[k:string]:any` on demand.

**Comment by SassNinja** [comment] 2022-10-11 08:14
@dohomi I've submitted a PR for this now

Instead of adding a new option for only a specific use case, I've added an option to customise all options passed though to json-schema-to-typescript as this provides maximum flexibility.

I'm also facing the issue that I want `additionalProperties` set false. Once my PR is merged this can easily be achieved:

```
storyblok-generate-ts compilerOptions.additionalProperties=false
```

**Closed** 2022-10-12 04:37 UTC

**Comment by dohomi** [comment] 2022-10-12 04:47
thanks @SassNinja v1.7 is released with the compiler options.
